#!/usr/bin/env python3
"""Generate REST + MCP reference pages from live engine sources.

Reads:
  VALORBRAIN_OPENAPI   (default /opt/valorbrain/docs/reference/openapi.yaml)
  VALORBRAIN_CATALOG   (default /opt/valorbrain/src/tool-catalog.ts)

Writes, so the docs site cannot drift from the engine without a rebuild:
  public/openapi.yaml
  public/openapi.json
  content/docs/api/generated-rest.mdx
  content/docs/api/generated-mcp.mdx
"""
from __future__ import annotations

import json
import os
import re
import sys
from collections import defaultdict
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("generate-reference: PyYAML is required (python3 -c 'import yaml')")

ROOT = Path(__file__).resolve().parents[1]
OPENAPI_SRC = Path(
    os.environ.get("VALORBRAIN_OPENAPI", "/opt/valorbrain/docs/reference/openapi.yaml")
)
CATALOG_SRC = Path(
    os.environ.get("VALORBRAIN_CATALOG", "/opt/valorbrain/src/tool-catalog.ts")
)
PUBLIC_REST = "https://valorbrain-api.valor.digital"


def schema_brief(schema: object, depth: int = 0) -> str:
    if schema is None or depth > 3:
        return ""
    if not isinstance(schema, dict):
        return str(schema)
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    t = schema.get("type")
    if t == "object" or "properties" in schema:
        props = schema.get("properties") or {}
        req = set(schema.get("required") or [])
        parts = []
        for name, sub in list(props.items())[:24]:
            star = "*" if name in req else ""
            inner = schema_brief(sub, depth + 1)
            parts.append(f"`{name}`{star}" + (f" ({inner})" if inner else ""))
        more = "" if len(props) <= 24 else f", …+{len(props) - 24}"
        return "object( " + ", ".join(parts) + more + " )"
    if t == "array":
        return f"array[{schema_brief(schema.get('items'), depth + 1)}]"
    if "enum" in schema:
        return "enum(" + ", ".join(str(x) for x in schema["enum"][:12]) + ")"
    if t:
        return str(t)
    return ""


def emit_rest(spec: dict) -> str:
    by_tag: dict[str, list[str]] = defaultdict(list)
    for path, methods in (spec.get("paths") or {}).items():
        if not isinstance(methods, dict):
            continue
        for method, op in methods.items():
            if method.startswith("x-") or not isinstance(op, dict):
                continue
            if method.lower() not in {"get", "post", "put", "patch", "delete", "options", "head"}:
                continue
            tags = op.get("tags") or ["Untagged"]
            tag = tags[0]
            summary = op.get("summary") or ""
            desc = (op.get("description") or "").strip().replace("\n", " ")
            auth = "none" if op.get("security") == [] else "bearer"
            params = op.get("parameters") or []
            q = [
                f"`{p.get('name')}`" + ("*" if p.get("required") else "")
                for p in params
                if isinstance(p, dict)
            ]
            body = ""
            rb = op.get("requestBody") or {}
            content = (rb.get("content") or {}).get("application/json") or {}
            if content.get("schema"):
                body = schema_brief(content["schema"])
            lines = [
                f"### `{method.upper()} {path}`",
                "",
                f"{summary}" + (f" — {desc}" if desc and desc != summary else ""),
                "",
                f"- Auth: {auth}",
            ]
            if q:
                lines.append("- Params: " + ", ".join(q))
            if body:
                lines.append(f"- Body: {body}")
            oid = op.get("operationId")
            if oid:
                lines.append(f"- operationId: `{oid}`")
            lines.append("")
            lines.append("```yaml")
            lines.append(yaml.dump({method: op}, sort_keys=False, allow_unicode=True).rstrip())
            lines.append("```")
            lines.append("")
            by_tag[tag].append("\n".join(lines))

    chunks = [
        "---",
        "title: REST (generated)",
        "description: Every path in the engine OpenAPI, regenerated at docs build. Do not edit.",
        "---",
        "",
        "{/* generated by scripts/generate-reference.py — do not edit */}",
        "",
        f"Source: `{OPENAPI_SRC}`. Public base: `{PUBLIC_REST}`.",
        "Admin and ops routes are listed because they exist; a tenant token will 403 them.",
        "",
        f"**{sum(len(v) for v in by_tag.values())} operations** across "
        f"{len(by_tag)} tags.",
        "",
    ]
    for tag in sorted(by_tag):
        chunks.append(f"## {tag}")
        chunks.append("")
        chunks.extend(by_tag[tag])
    return "\n".join(chunks)


CATALOG_RE = re.compile(
    r'E\(\s*"([^"]+)"\s*,\s*"([^"]+)"\s*(?:,\s*\{([^}]*)\})?\s*\)',
    re.MULTILINE,
)


def emit_mcp(src: Path) -> str:
    text = src.read_text()
    rows = []
    for m in CATALOG_RE.finditer(text):
        name, toolset, extra = m.group(1), m.group(2), m.group(3) or ""
        status = "stable"
        alias = ""
        rest = ""
        note = ""
        sm = re.search(r'status:\s*"([^"]+)"', extra)
        if sm:
            status = sm.group(1)
        am = re.search(r'aliasOf:\s*"([^"]+)"', extra)
        if am:
            alias = am.group(1)
        rm = re.search(r'restTwin:\s*"([^"]+)"', extra)
        if rm:
            rest = rm.group(1)
        nm = re.search(r'note:\s*"([^"]+)"', extra)
        if nm:
            note = nm.group(1)
        rows.append((toolset, name, status, alias, rest, note))

    by = defaultdict(list)
    for toolset, name, status, alias, rest, note in rows:
        bits = [f"**`{name}`**"]
        if status != "stable":
            bits.append(f"`{status}`")
        if alias:
            bits.append(f"→ `{alias}`")
        if rest:
            bits.append(f"REST `{rest}`")
        if note:
            bits.append(note)
        by[toolset].append("- " + " · ".join(bits))

    chunks = [
        "---",
        "title: MCP catalog (generated)",
        "description: src/tool-catalog.ts, regenerated at docs build. Do not edit.",
        "---",
        "",
        "{/* generated by scripts/generate-reference.py — do not edit */}",
        "",
        f"Source: `{CATALOG_SRC}`. New tokens default to the **agent** toolset.",
        f"**{len(rows)} names** in the catalog (canonical + aliases + deprecated).",
        "",
    ]
    for toolset in ("agent", "graph", "ops"):
        chunks.append(f"## {toolset}")
        chunks.append("")
        chunks.extend(by.get(toolset, []))
        chunks.append("")
    return "\n".join(chunks)


def main() -> int:
    api_dir = ROOT / "content" / "docs" / "api"
    public = ROOT / "public"
    if not OPENAPI_SRC.is_file():
        if (api_dir / "generated-rest.mdx").is_file() and (public / "openapi.json").is_file():
            print("generate-reference: engine OpenAPI missing, using committed snapshot")
            return 0
        print(f"generate-reference: missing {OPENAPI_SRC}", file=sys.stderr)
        return 1
    spec = yaml.safe_load(OPENAPI_SRC.read_text())
    spec["servers"] = [
        {"url": PUBLIC_REST, "description": "Hosted engine REST"},
        {"url": "http://localhost:7438", "description": "Local engine (self-hosted)"},
    ]

    public = ROOT / "public"
    public.mkdir(exist_ok=True)
    (public / "openapi.yaml").write_text(
        yaml.safe_dump(spec, sort_keys=False, allow_unicode=True), encoding="utf-8"
    )
    (public / "openapi.json").write_text(
        json.dumps(spec, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )

    api_dir = ROOT / "content" / "docs" / "api"
    api_dir.mkdir(parents=True, exist_ok=True)
    (api_dir / "generated-rest.mdx").write_text(emit_rest(spec), encoding="utf-8")
    if CATALOG_SRC.is_file():
        (api_dir / "generated-mcp.mdx").write_text(emit_mcp(CATALOG_SRC), encoding="utf-8")
    else:
        print(f"generate-reference: skip MCP catalog ({CATALOG_SRC} missing)", file=sys.stderr)

    rest_bytes = (api_dir / "generated-rest.mdx").stat().st_size
    json_bytes = (public / "openapi.json").stat().st_size
    print(
        f"generate-reference: openapi.json={json_bytes}B generated-rest.mdx={rest_bytes}B"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
